import type { Metadata } from "next";
import {ClerkProvider} from '@clerk/nextjs'


import { Inter } from 'next/font/google'
import "./globals.css";
const inter = Inter({ subsets: ['latin'] })




export const metadata: Metadata = {
  title: "Cofat One",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/logo.svg",

  }

};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className} >
          <main className="h-dvh">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
